services:
#    aakron_sale.example:
#        class: Aakron\Bundle\SaleBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    aakron_sale.quote_type_extension:
        class: Aakron\Bundle\SaleBundle\Form\Extension\QuoteTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Oro\Bundle\SaleBundle\Form\Type\QuoteType }
#    aakron_sale.quote_product_type_extension:
#        class: Aakron\Bundle\SaleBundle\Form\Extension\QuoteProductTypeExtension
#        tags:
#            - { name: form.type_extension, extended_type: Oro\Bundle\SaleBundle\Form\Type\QuoteProductType }
#    aakron_sale.service.quote_request_handler:
#        class: 'Aakron\Bundle\SaleBundle\Model\CustomQuoteRequestHandler'
#        arguments:
#            - "@doctrine"
#            - "@request_stack"
#            - '%oro_account.entity.account.class%'
#            - '%oro_contact.entity.class%'