config:
    paths:
        # for the Select2View class
        'aakroncscapi/js/app/views/select2-view': 'bundles/aakroncscapi/js/app/views/select2-view.js'
        # for the Select2Component class
        'aakroncscapi/js/app/components/select2-component': 'bundles/aakroncscapi/js/app/components/select2-component.js'